engines:
  eslint:
    enabled: true
ratings:
   paths:
   - client/src/app/**
   - server/src/**
exclude_paths:
  - "client/src/app/lib/**/*"
  - "server/migrations/**/*"
  - "server/src/**/test*.js"
  - "test*.js"
