language: node_js
node_js:
  - "5"
  - "4"

env:
  - CXX=g++-4.8

services:
  - rabbitmq

addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

after_script:
  - cd client && npm run build && npm test
  - cd server && npm run codeclimate && npm run coveralls
