---
# A list of directives for the events section.
nginx_events_params:
  - worker_connections 512

# A list of hashs that define the servers for nginx,
# as with http parameters. Any valid server parameters
# can be defined here.
nginx_http_params:
  - sendfile on
  - access_log /var/log/nginx/access.log

nginx_sites:
 default:
     - listen {{ http_port }}
     - server_name _
     - root {{ api_dir }}/client/build
     - index index.html
     - location /api/ {
         proxy_pass http://localhost:{{ api_port }};
         break;
       }
     - location / {
         try_files $uri /index.html;
       }

# A list of hashs that define additional configuration
nginx_configs:
  proxy:
      - proxy_set_header X-Real-IP  $remote_addr
      - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
  gzip:
      - gzip on
      - gzip_disable msie6
      - gzip_static on
