web:
  build: ./
  volumes:
    - ".:/app"
  expose:
    - "3000"
  links:
    - "rabbitmq"
    - "postgres"
  command: npm start

postgres:
  image: postgres
  expose:
    - "5432"
rabbitmq:
  image: rabbitmq
  expose:
    - "5672"
